# GKE only
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: simple-http-metrics
  namespace: project
  labels:
    app.kubernetes.io/name: simple-http-metrics
    app.kubernetes.io/part-of: google-cloud-managed-prometheus
spec:
  endpoints:
    - port: 8000
      scheme: http
      interval: 30s
      path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: simple-http-api
