apiVersion: v1
kind: Secret
metadata:
  namespace: project
  name: simple-http-secrets
# apparently, type: opaque + stringData: can be used for k8s native encoding
data:
  API_URL: aHR0cDovL3NpbXBsZS1odHRwLXN2YzoyMzQ2Cg==
  API_URI: L3RvZG9z
  API_PORT: ODA2MQ==
  STATIC_CACHE_DIR: L3RtcC9zaW1wbGUtaHR0cA==
  STATIC_CACHE_EXPIRY: NjAw
  STATIC_BASE_URL: aHR0cHM6Ly9waWNzdW0ucGhvdG9zLw==
  STATIC_TARGET_ID: MTAw
  STATIC_PORT: ODA2MA==
  REDIS_URL: cmVkaXM6Ly9yZWRpczo2Mzc5LzAK
  pguser: c2ltcGxlLWh0dHAK
  pgpassword: c2ltcGxlLWh0dHAK
  RAND_URL: aHR0cHM6Ly9lbi53aWtpcGVkaWEub3JnL3dpa2kvU3BlY2lhbDpSYW5kb20K
