apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./../../base
patches:
  - path: statefulset.yaml
    target:
      kind: StatefulSet
      name: simple-http-stset
  - path: pg-backup-cron.yaml
    target:
      kind: CronJob
      name: simple-http-backup

namePrefix: stage-
