kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dummysite-controller-role
rules:
  - apiGroups: [""]
    # at the HTTP level, the name of the resource for accessing Pod
    # objects is "pods"
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
  - apiGroups: ["batch"]
    # at the HTTP level, the name of the resource for accessing Job
    # objects is "jobs"
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "patch", "delete", "update"]
  - apiGroups: ["stable.dwk"]
    resources: ["dummysites"]
    verbs: ["get", "list", "watch", "create", "delete"]
