apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: exercises
  name: ping-pong-dep
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ping-pong
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause:
            duration: 30s
        - analysis:
            templates:
              - templateName: cpu-usage-rate
            args:
              - name: namespace
                value: exercises
              - name: cpuThresholdCores
                value: "1"
        - setWeight: 75
        - pause:
            duration: 30s
  template:
    metadata:
      annotations:
        canary-cpu-stress-test: "ping-pong-canary-test-1"
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: xuanminator/ping-pong:3.4
          imagePullPolicy: Always
          ports:
            - name: ping
              containerPort: 8089
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: ping-pong-db-secret
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: ping-pong-db-secret
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: db
                  name: ping-pong-db-secret
          resources:
            requests:
              cpu: "30m"
              memory: "32Mi"
            limits:
              cpu: "60m"
              memory: "32Mi"
