apiVersion: v1
kind: Secret
metadata:
  name: ping-pong-db-secret
  namespace: exercises
type: Opaque
data: # NOT 'stringData'!! that will use the encoded string literally!
  password: dGhpc2NvdXJzZWlzdGhlYmVzdA==
  user: dGVydmV0dWxvYQ==
