apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: exercises
  name: ping-pong-stset
spec:
  serviceName: ping-pong-pg-svc # must match the headless svc
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-pg
  template:
    metadata:
      labels:
        app: ping-pong-pg
    spec:
      containers:
        - name: postgres
          image: postgres:13
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            exec:
              command: ["sh", "-c", 'pg_isready -U "$POSTGRES_USER"']
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: ping-pong-db-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: ping-pong-db-secret
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: db
                  name: ping-pong-db-secret
          # resources:
          #   requests:
          #     cpu: "30m"
          #     memory: "32Mi"
          #   limits:
          #     cpu: "60m"
          #     memory: "32Mi"
          volumeMounts:
            - name: ping-pong-pg-dat
              mountPath: /var/lib/postgresql/data
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: ping-pong-pg-dat
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
