apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./../../base
patches:
- path: statefulset.yaml
  target:
    kind: StatefulSet
    name: simple-http-stset

namePrefix: prod-
namespace: project-4-9-prod
