apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      namespace: exercises
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-log
          persistentVolumeClaim:
            claimName: pvc-1-11
        - name: config-volume
          configMap:
            name: log-output-configmap-2-5
      containers:
        # logger
        - name: log-output-logger
          image: LOGGER/IMAGE
          imagePullPolicy: IfNotPresent
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-configmap-2-5
                  key: MESSAGE
          volumeMounts:
            - name: shared-log
              mountPath: /tmp/logs
            - name: config-volume
              mountPath: /tmp/config
          resources:
            requests:
              cpu: "30m"
              memory: "64Mi"
            limits:
              cpu: "60m"
              memory: "64Mi"
        # fetcher
        - name: log-output-fetcher
          image: FETCHER/IMAGE
          imagePullPolicy: Always
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-configmap-2-5
                  key: MESSAGE
          volumeMounts:
            - name: shared-log
              mountPath: /tmp/logs
            - name: config-volume
              mountPath: /tmp/config
          resources:
            requests:
              cpu: "30m"
              memory: "64Mi"
            limits:
              cpu: "60m"
              memory: "64Mi"
