apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: greeter-dest-rule
  namespace: exercises
spec:
  host: greeter-svc
  subsets:
    - name: v1-subset
      labels:
        version: v1
    - name: v2-subset
      labels:
        version: v2
