# use: `helm upgrade -f this/file.yaml my-nats oci://registry-1.docker.io/bitnamicharts/nats`

auth:
  enabled: false

image:
  registry: docker.io
  repository: bitnamilegacy/nats
  tag: 2.11.8-debian-12-r0

metrics:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/nats-exporter
    tag: 0.17.3-debian-12-r8
  serviceMonitor:
    enabled: true
    namespace: prometheus
